-- board 테이블 작성

CREATE TABLE board(
	bno number(8) PRIMARY KEY,
	title varchar2(100) NOT NULL,
	content varchar2(2000) NOT NULL,
	writer varchar2(50) NOT NULL,
	ragdate DATE DEFAULT sysdate
);

CREATE SEQUENCE BOARD_SEQ;

INSERT INTO BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES(BOARD_SEQ.NEXTVAL, 'title', 'content1', 'user1');

INSERT INTO STUDENTTBL(ID,NAME) VALUES(STUDENTTBL_SEQ.NEXTVAL, '홍길동');
INSERT INTO STUDENTTBL(ID,NAME) VALUES(STUDENTTBL_SEQ.NEXTVAL, '성춘향');

INSERT INTO STUDENTTBL(NAME) VALUES( '홍길동');
INSERT INTO STUDENTTBL(NAME) VALUES( '성춘향');

DROP TABLE HTE_STUDENTTBL;

DROP SEQUENCE BOARD_SEQ;

INSERT INTO TEAM(TEAM_NAME) VALUES('victory');
INSERT INTO TEAM(TEAM_NAME) VALUES('hope');

INSERT INTO TEAM_MEMBER(USER_NAME, TEAM_TEAM_ID) VALUES('홍길동', 1);
INSERT INTO TEAM_MEMBER(USER_NAME, TEAM_TEAM_ID) VALUES('성춘향', 2);

SELECT *
FROM TODO t 
WHERE T.COMPLETED =1;

SELECT *
FROM TODO t 
WHERE T.COMPLETED =0;

SELECT *
FROM TODO t 
WHERE T.IMPORTANTED  =1;
